### ISSUE TITLE
Panic when external umount

### ISSUE THREAD

**Issue by ho-229** [Sherlock-Holo/fuse3#91]
I ran `fuse3` in multi-threaded tokio-runtime and mount privileged, when I umount externally, tokio(v1.37) will panic from time to time.

```
thread 'tokio-runtime-worker' panicked at /home/ho229/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:375:22:
JoinHandle polled after completion
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: tokio::runtime::task::harness::Harness<T,S>::try_read_output
   3: <tokio::runtime::task::join::JoinHandle<T> as core::future::future::Future>::poll
   4: fuse3::raw::session::MountHandleInner::inner_unmount::{{closure}}
   5: tokio::runtime::task::core::Core<T,S>::poll
   6: tokio::runtime::task::harness::Harness<T,S>::poll
   7: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
   8: tokio::runtime::scheduler::multi_thread::worker::Context::run
   9: tokio::runtime::context::scoped::Scoped<T>::set
  10: tokio::runtime::context::runtime::enter_runtime
  11: tokio::runtime::scheduler::multi_thread::worker::run
  12: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  13: tokio::runtime::task::core::Core<T,S>::poll
  14: tokio::runtime::task::harness::Harness<T,S>::poll
  15: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Xuanwo** [comment]
cc @ho-229 would you like to give PR https://github.com/Sherlock-Holo/fuse3/pull/94 a try?

**Comment by ho-229** [comment]
This patch can fix the problem, I will move on when it release.

**Comment by ho-229** [comment]
Done #94
